export const products = [
  {
    id: 1,
    nombre: "Hamburguesa",
    descripcion: "A delicious burger with juicy meat, melted cheese, crispy lettuce, fresh tomato, and special sauce, all in a soft bun.",
    etiqueta: "Burger",
    precio: 9.99,
    imagen: "https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
  },
  {
    id: 2,
    nombre: "Pizza",
    descripcion: "A freshly baked pizza with a tomato sauce base, melted mozzarella, and your favorite toppings, all on a crispy crust.",
    etiqueta: "Pizza",
    precio: 12.99,
    imagen: "https://images.pexels.com/photos/1653877/pexels-photo-1653877.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 3,
    nombre: "Pollo Frito",
    descripcion: "Seasoned and breaded chicken pieces, fried to perfection until golden and crispy on the outside, and juicy and tender on the inside.",
    etiqueta: "Fried Chicken",
    precio: 8.49,
    imagen: "https://images.pexels.com/photos/2338407/pexels-photo-2338407.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 4,
    nombre: "Plato Mixto",
    descripcion: "A hearty plate with a mix of delicious flavors, including grilled beef, grilled chicken, smoked pork ribs, French fries, and roasted vegetables.",
    etiqueta: "Mixed Plate",
    precio: 15.99,
    imagen: "https://images.pexels.com/photos/20067063/pexels-photo-20067063/free-photo-of-plato-cena-comida-pez.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 5,
    nombre: "Tacos",
    descripcion: "Corn tortillas filled with seasoned meat, chopped onion, fresh cilantro, and served with spicy sauce, lime, and fresh garnishes like avocado and radishes.",
    etiqueta: "Tacos",
    precio: 10.99,
    imagen: "https://images.pexels.com/photos/4958641/pexels-photo-4958641.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 6,
    nombre: "Sushi",
    descripcion: "Slices of fresh fish, perfectly cooked sushi rice, nori seaweed, and a variety of fresh and tasty ingredients, all rolled into an exquisite sushi piece.",
    etiqueta: "Sushi",
    precio: 18.99,
    imagen: "https://images.pexels.com/photos/2098085/pexels-photo-2098085.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
];
